apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 3000       # port du service (interne cluster)
      targetPort: 3000 # port du conteneur (dans le pod)
      nodePort: 30007  # port sur la machine hôte
